### ISSUE TITLE
Confused about create_sequences.py

### ISSUE THREAD

**Issue by morganrivers** [0xideas/whale-gpt#3]
For this part,
```
    new_data = pd.DataFrame(
        new_rows,
        columns=[
            "sequenceId",
            "itemPosition",
            "Coda",
            "Ornamentation",
            "Duration",
            "VocalizationChange",
            "SpeakerChange",
        ],
    )
    new_data.to_csv(
        "data/whale-sequences.csv",
        index=False,
        sep=",",
        decimal=".",
        float_format=lambda x: f"{x:.7f}",
    )
```
It seems like we're trying to save some useful way to view data, but we're not including the whale which is emitting each coda?
If there are 3+ whales, then we would have some underspecified situation where we don't know if we're switching back to the original whale or to some other whale

**Comment by 0xideas** [comment]
This is an old script that isn't relevant to the current "script" project, I'll remove it.

**Comment by 0xideas** [comment]
Done!
