### ISSUE TITLE
What is the TsToAbs?

### ISSUE THREAD

**Issue by morganrivers** [0xideas/whale-gpt#4]
whale-dialogue-script.csv has nonzero value for TsToAbs for the first and last row. I thought this was a delta between a given coda and the previous (or the next).
But if both the first and last emitted coda have nonzero TsToAbs, then neither interpretation makes sense.

**Comment by morganrivers** [comment]
```
        ts_to_baseline = rec_data.iloc[0, :]["TsTo"]
        for i, row in rec_data.iterrows():
            if row["Coda"] not in [100, -1]:
                ...
                ...
                ...
                row = (
                    rec_counter,
                    item_position,
                    row["Whale"],
                    row["Coda"],
                    ornamentation,
                    synchrony,
                    row["Duration"],
                    row["TsTo"] - ts_to_baseline,
                )
```

I see based on the code in `1b_create_dialogue_script.py` this is being reset each time there's a new sequenceid (a new filename in the original dataset we're getting this from). So I see it's not a delta from previous, it's a delta from the start of the sound recording corresponding to this filename.

**Comment by morganrivers** [comment]
Actually, so there's still an issue: the only reason the first TsToAbs should be 0 is if there is a "100" coda, which  is just whether the next row contains ornamentation.
The first row should be 0, but it's not (it's 0.033950000000004366)

**Comment by 0xideas** [comment]
Okay, fixed it :)
